# Generated by Django 4.2.1 on 2023-05-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_talk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Talk',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='nama',
            new_name='name',
        ),
    ]
